<p style="text-align:center">
    <a href="https://skills.network/?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDA0321ENSkillsNetwork928-2022-01-01" target="_blank">
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/assets/logos/SN_web_lightmode.png" width="200" alt="Skills Network Logo"  />
    </a>
</p>

# **Collecting Job Data Using API**

### Objectives

*   Collect job data from Jobs API
*   Store the collected data into an excel spreadsheet.

In [77]:
# Requirements
import requests
api_url="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DA0321EN-SkillsNetwork/labs/module%201/Accessing%20Data%20Using%20APIs/jobs.json"
response = requests.get(api_url)
jobs_data = response.json()

### 1. Write a function to get the number of jobs for the Python technology

In [78]:
def count_jobs_technology(technology):
    job_count = 0
    
    for job in jobs_data:
        key_skills = job.get("Key Skills")
        if technology in key_skills:
            job_count += 1
    
    return job_count

In [79]:
python_jobs = count_jobs_technology('Python')
print(f"Number of jobs for Python technology: {python_jobs}")

Number of jobs for Python technology: 1173

### 2. Write a function to find number of jobs in US for a location

In [80]:
def count_jobs_Location(location):
    job_count = 0
    
    for job in jobs_data:
        city = job.get('Location')
        if city == location:
            job_count += 1
   
    return location, job_count

In [82]:
some_cities = ["Los Angeles", "New York", "San Francisco", "Washington DC", "Seattle"] # Example cities
for city in some_cities:
    location, job_count = count_jobs_Location(city) 
    print(f"Number of jobs for location {location}: {job_count}")

Number of jobs for location Los Angeles: 640
Number of jobs for location New York: 3226
Number of jobs for location San Francisco: 435
Number of jobs for location Washington DC: 5316
Number of jobs for location Seattle: 3375

### 3.  Store the results in an excel file

#### 3.1 Collect the number of job postings and write the results in an excel spreadsheet for the following languages:

*   C
*   C#
*   C++
*   Java
*   JavaScript
*   Python
*   Scala
*   Oracle
*   SQL Server
*   MySQL Server
*   PostgreSQL
*   MongoDB

In [83]:
data_technology = []
technologies = [
    "C", "C#", "C++", "Java", "JavaScript", "Python",
    "Scala", "Oracle", "SQL Server", "MySQL Server",
    "PostgreSQL", "MongoDB"
]
for technology in technologies:
    data_technology.append((technology, count_jobs_technology(technology)))

In [84]:
import pandas as pd

In [85]:
df1 = pd.DataFrame(data_technology, columns=["Technology", "Job Postings"])
print(df1)

      Technology  Job Postings
0              C         13498
1             C#           333
2            C++           305
3           Java          2609
4     JavaScript           355
5         Python          1173
6          Scala            33
7         Oracle           784
8     SQL Server           250
9   MySQL Server             0
10    PostgreSQL            10
11       MongoDB           174

Convert dataframe to excel

In [86]:
file_path = "job-postings.xlsx"
df1.to_excel(file_path, index=False, sheet_name="Jobs per Technology")

#### 3.2 Collect the number of job postings and write the results in an excel spreadsheet for the locations:

* Los Angeles
* New York
* San Francisco
* Washington DC
* Seattle
* Austin
* Detroit

In [87]:
data_location = []
locations = [
    "Los Angeles",
    "New York",
    "San Francisco",
    "Washington DC",
    "Seattle",
    "Austin",
    "Detroit"
]
for location in locations:
    data_location.append(count_jobs_Location(location))

In [88]:
df2 = pd.DataFrame(data_location, columns=['Location', 'Job Postings'])
print(df2)

        Location  Job Postings
0    Los Angeles           640
1       New York          3226
2  San Francisco           435
3  Washington DC          5316
4        Seattle          3375
5         Austin           434
6        Detroit          3945

Write to the previously created excel file

In [89]:
with pd.ExcelWriter(file_path, engine="openpyxl", mode="a") as writer:
    df2.to_excel(writer, index=False, sheet_name="Jobs per Location")